spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_try?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456Aa
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456Aa

#spring boot集成mybatis的方式打印sql
logging:
  level:
    work.jimmygo.springboottry.mapper: DEBUG




#spring集成Mybatis环境
#pojo别名扫描包 mybatis.type-aliases-package=com.itheima.domain
#加载Mybatis映射文件
mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: work.jimmygo.springboottry.model