spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.182.211:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
#spring boot集成mybatis的方式打印sql
logging:
  level:
    work.jimmygo.springboottry.mapper: DEBUG




#spring集成Mybatis环境
#pojo别名扫描包 mybatis.type-aliases-package=com.itheima.domain
#加载Mybatis映射文件
mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: work.jimmygo.springboottry.model